### ISSUE TITLE
Seg fault

### ISSUE THREAD

**Issue by DanCardin** [voldikss/vim-floaterm#45] opened 2020-02-22 14:37 UTC
(if the mappings matter at all)
Given:
```
nmap <silent> <Leader>fp :FloatermNew python<cr>
tnoremap  <silent> <Leader>ft <C-\><C-n>:FloatermToggle<CR>
```

I regularly see a segfault when:
* open vim
* <leader>fp
* <leader>ft

If I instead, `FloatermToggle` before running `FloatermNew python`, it does not segfault.

I want to say there are other circumstances through which I've triggered this behavior, but this is the only one i can trigger on demand right now.

**Comment by voldikss** [comment] 2020-02-22 14:50
Do you have other configurations about this plugin? I tried your keymaps and didn't reproduce the issue

**Comment by DanCardin** [comment] 2020-02-22 15:45
I can repro, with just
```
set nocompatible
set runtimepath^=~/.local/share/nvim/site/plugged/vim-floaterm/

nmap <silent> <Leader>fp :FloatermNew python<cr>
tnoremap  <silent> <Leader>ft <C-\><C-n>:FloatermToggle<CR>

syntax on
filetype plugin indent on
```

OS: Macos
Insofar as it might matter, nvim is coming from nix
```
NVIM v0.4.2
Build type: Release
LuaJIT 2.1.0-beta3
Compilation:
Compiled by nixbld1

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/2hg5nc9l57691wgplplqnhjxz5rqf7sy-neovim-unwrapped-0.4.2/share/nvim
```

**Comment by DanCardin** [comment] 2020-02-22 16:31
In fact, updating my nix channels upgraded me to 0.4.3, which fixes this segfault (as we as another one i remembered how to repro). I'm not sure if this is nix-related, or nvim version related.

**Comment by voldikss** [comment] 2020-02-26 00:23
Close this issue since it might be caused by version things. If it still occurs for nvim whose version is higher than 0.4.3, feel free to reopen this issue.

**Closed by voldikss** 2020-02-26 00:23 UTC
Labels: cannot reproduce
