### ISSUE TITLE
Ranger wrapper word wraps preview when you change selection

### ISSUE THREAD

**Issue by ginsburgnm** [voldikss/vim-floaterm#120] opened 2020-05-26 18:32 UTC
- [x] Please make sure you have looked through the [F.A.Q.](https://github.com/voldikss/vim-floaterm/#faq) first.

- [x] Please make sure you are using the latest version of the plugin.

- [x] Please use English as far as possible.

### Describe the bug
Ranger wraps the preview output of a file around if you use the ranger wrapper. Meaning the more you change what file you're looking at the more artifacts appear in the window. (2 screenshots attached)

If you run `FloatermNew` and just open ranger from the shell, ranger acts as it normally would. (Screenshot attached)

### To Reproduce

- Use the minimal vimrc

  ```vim
  set nocompatible
  set hidden
  set termguicolors
  set runtimepath^=/path/to/vim-floaterm
  filetype plugin indent on
  syntax on
  ```

- Steps to reproduce the behavior:

  1. Use minimal vimrc
  2. install vim 8.2
  3. open vim 
  4. run `FloatermNew ranger`
  5. scroll through the files and see the ranger viewer become incomprehensible

### Enviroment
 - OS [e.g. Arch Linux]: Ubuntu 18.04
 - Version [e.g. NVIM v0.5.0-fa9b057]: vim 8.2
 - Checkhealth info [run `:checkhealth` and post the messages]: 

  `Not an editor command: checkhealth`

### Screenshots(Optional, GIF is better)
Normal vimrc file
![Screenshot with my normal vimrc](https://user-images.githubusercontent.com/5425723/82936385-82e3db80-9f5c-11ea-8c75-dd5673030530.png)

Minimal vimrc file
![Screenshot with minimal vimrc](https://user-images.githubusercontent.com/5425723/82936397-870ff900-9f5c-11ea-9e80-2cbca6e9616a.png)

normal vimrc file but I just ran `FloatermNew` and then opened ranger
![Screenshot of running ranger in just a shell](https://user-images.githubusercontent.com/5425723/82936551-c2122c80-9f5c-11ea-8eee-9593233dbdf9.png)

**Comment by voldikss** [comment] 2020-05-27 02:01
Thanks.

Actually I've found this issue before, but I couldn't figure out the cause of the problem. However, I didn't pay much attention to it as I mainly use neovim, and this only occurs in vim. 

It seems the bug of vim(not quite sure). Try `:source` the following vimscript and you'll get exactly the same issue.
```vim
let bufnr = term_start('ranger', {'hidden': 1})
split
execute 'buffer ' . bufnr
```

So currently there are no solutions for this issue. You can choose either to close this issue or stay it opened.

**Comment by ginsburgnm** [comment] 2020-05-27 13:52
@voldikss I think I'd like to leave it open in the event that someone else finds this issue.

**Comment by voldikss** [comment] 2021-01-08 09:34
Can confirm this is a vim/ranger bug, but I don't have time to make a issue... 

```vim
:let buf = term_start('ranger', #{hidden: 1})
<C-w>v
:execute 'buffer' . buf
```

I feel this issue won't get fixed in a long time.

**Comment by hanleylee** [comment] 2021-08-09 02:14
I meet this issue too

**Comment by tracyone** [comment] 2022-01-17 13:57
> Can confirm this is a vim/ranger bug, but I don't have time to make a issue...
> 
> ```viml
> :let buf = term_start('ranger', #{hidden: 1})
> <C-w>v
> :execute 'buffer' . buf
> ```
> 
> I feel this issue won't get fixed in a long time.

@voldikss specify the term_cols and term_rows option will fix this issue.

**Closed** 2022-01-18 09:07 UTC
Labels: bug, editor:vim8, integration:ranger, bug:upstream

**Comment by voldikss** [comment] 2022-01-18 09:08
Thanks @tracyone
