### ISSUE TITLE
Meaning of s:floatermSettings?

### ISSUE THREAD

**Issue by ywpkwon** [voldikss/vim-floaterm#97] opened 2020-04-18 11:06 UTC
I usually have `scrolloff=3` in my vim setting. (3 more lines at screen top/bottom boundaries).  

In `Floaterm`, I would like to have it as `scrolloff=0` since I may run `ranger` for example. And I want the setting come back to 3 for normal vim buffers. 

I thought `s:floatermSettings` is the way to go:
```
  function s:floatermSettings()
      setlocal scrolloff=0
      " more settings
  endfunction
  autocmd FileType floaterm call s:floatermSettings()
```
It worked for `Floaterm`. `scrolloff` becomes 0 when I start `Floaterm`. However, when I got back to normal buffers, it seemed `scrolloff` is still zero. Would you please advise how I should setup?

**Comment by voldikss** [comment] 2020-04-18 13:55
> In Floaterm, I would like to have it as scrolloff=0 since I may run ranger for example

You do not have to do that. Even in terminal buffer the `scrolloff` is set to `0`, it won't affect your operation. 

> However, when I got back to normal buffers, it seemed scrolloff is still zero

Reproduced, but it's not a bug of this plugin. This issues still occurs without vim-floaterm, for testing:
- open two windows in nvim
- in one window, `setlocal scrolloff=0` 
- jump to another window, you will find `scrolloff` is still `0`

**Comment by ywpkwon** [comment] 2020-04-18 21:08
Thanks for your quick response! 

> You do not have to do that. Your operation won't be affected even if the `scrolloff` is not set to `0` in terminal buffer.

I'm wondering if I do not have to do this. Please take a look at this GIF. You'll see the bottom part of the previous command result (`neofetch`). When I set `setlocal scrolloff=0`, there was no such behavior. Note that, for the ranger "plugin", I didn't need to set `scrolloff` since the term doesn't have anything above. However, in general, `Floaterm`, I may do something else (neofetch, ls, etc.) before running ranger, and it seemed that `scrolloff` affects ranger. Am I missing something?

![Screencast-2020-04-18T13:47:29-07:00](https://user-images.githubusercontent.com/18429284/79671003-c7b96d00-817b-11ea-9ff0-b638740bed84.gif)

> Reproduced, but it's not a bug of this plugin. This issues still occurs without vim-floaterm, for testing:
> 
> * open two windows in nvim
> * in one window, `setlocal scrolloff=0`
> * jump to another window, you will find `scrolloff` is still `0`

Thanks for the clarification. In some other vim-terminal repo, I saw a part like:
```
    augroup TerminalBehavior
      autocmd!
      autocmd TermOpen * setlocal listchars= nonumber norelativenumber nowrap winfixwidth scrolloff=0 noruler signcolumn=no
      autocmd TermOpen * startinsert
      autocmd TermClose * set showmode ruler scrolloff=3
    augroup END
```
I was using this kind of part in my `init.vim` to switch values back to normal. I thought `s:floatermSettings()` do this temporary switch for me. I think it's okay.

Thanks again for the great plugin!!

**Comment by voldikss** [comment] 2020-04-19 00:53
> autocmd TermClose * set showmode ruler scrolloff=3

It only set `scrolloff` to 3 when the terminal exits, but do nothing when you just hide the terminal.

I recommend this:
```vim
function s:floatermSettings()
    setlocal scrolloff=0
    autocmd BufLeave <buffer> ++once set scrolloff=3
endfunction
autocmd FileType floaterm call s:floatermSettings()
```

**Comment by voldikss** [comment] 2020-04-19 00:54
I think this issue can get fixed, so let me close it.

**Closed by voldikss** 2020-04-19 00:54 UTC

**Comment by ywpkwon** [comment] 2020-04-19 01:26
Thanks! I'll use it.
