### ISSUE TITLE
Lazygit quit bug

### ISSUE THREAD

**Issue by timsofteng** [voldikss/vim-floaterm#170] opened 2020-09-05 10:00 UTC
1. Open lazygit by :FloatermNew lazygit.
2. Try to close it by press "q" of Esc. And we will get empty terminal. 
3. If we try to close it by `let g:floaterm_keymap_kill` we will got errors messages.

Can you please fix it?
Thanks

**Comment by voldikss** [comment] 2020-09-05 10:21
I cannot reproduce it. Could you give me some screenshots?

**Comment by timsofteng** [comment] 2020-09-05 10:37
Yes, sure. Check the gif please. 
Ctrl-t+q is just my shortcut for `let g:floaterm_keymap_kill   = '<C-t>q'`

Expected befavior:
Close floaterm as well as lazygit by pressing "q" in lazygit.

![Peek 2020-09-05 13-31](https://user-images.githubusercontent.com/51912173/92303343-897ee780-ef7c-11ea-83b3-792e4593bcdb.gif)

**Comment by voldikss** [comment] 2020-09-05 11:15
I have seen the whole gif but still have no ideas. It might be related to your other configs.

Please try reproducing this issue with the [minimal vimrc](https://github.com/voldikss/vim-floaterm/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#to-reproduce) (Actually you should do it at first, and also post your vim/nvim version, as described in the issue template) and give me the feedback.

**Comment by timsofteng** [comment] 2020-09-05 11:53
I can't do it with minimal vimrc because I'm using raw vim and plugins trigger from vimrc.

Here is my vimrc file if it's make sense


"Plugins configs
source $HOME/.vim/plug-config/fzf.vim
source $HOME/.vim/plug-config/floaterm.vim
source $HOME/.vim/plug-config/repeat.vim
source $HOME/.vim/plug-config/ticket.vim
source $HOME/.vim/plug-config/fugitive.vim
source $HOME/.vim/plug-config/ctrlsf.vim
source $HOME/.vim/plug-config/deoplete.vim
source $HOME/.vim/plug-config/closetag.vim
source $HOME/.vim/plug-config/coc.vim
source $HOME/.vim/plug-config/ale.vim
source $HOME/.vim/plug-config/fern.vim

"set vim plugins
source $HOME/.vim/vim-plug/plugins.vim

" Edit vimr configuration file
nnoremap confe :vs $MYVIMRC<CR>
" Reload vims configuration file
nnoremap confr :source $MYVIMRC<CR>
"vimplug
nnoremap vimplug :vs ~/.vim/vim-plug/plugins.vim<CR>

set autoread " detect when a file is changed
au BufEnter * :checktime

"added dialog before closing buffers
set confirm

" allow buffer switching without saving
"set hidden

set mouse=a
"Mouse windows resizing
set ttymouse=sgr

set tabstop=2 shiftwidth=2 expandtab

set nocompatible
filetype off

set diffopt+=vertical  " Always use vertical diffs

" Searching
set ignorecase " case insensitive searching
set smartcase " case-sensitive if expresson contains a capital letter
set hlsearch " highlight search results
set incsearch " set incremental search, like modern browsers

"Apperance
set number
set relativenumber
set linebreak " set soft wrapping
set cursorline " Highlight the line currently under cursor
"set ttyfast " faster redrawing


"Частота обновления вима
set updatetime=300

" Display command line’s tab complete options as a menu
set wildmenu

" Buffers line
"let g:airline#extensions#tabline#enabled = 1


"For correct appear in st-term
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

set termguicolors
"set t_Co=256
" Colorscheme
"set background=dark
set background=light
colorscheme solarized8

set encoding=utf-8
" Set font competable with icons
set guifont=DejavuSansMono\ Nerd\ Font\ 10

"Disable ability change all letters to lowercase
"in visual mode by press "u"
xnoremap u <nop>
"search word in visual mode by predding "//"
vnoremap // y/\V<C-R>=escape(@",'/\')<CR><CR>

"disable highlighting by double Esc
nnoremap <Esc><Esc> :noh <CR>

"jumping between buffers
nnoremap <Leader>n :bn <CR>
nnoremap <Leader>p :bp <CR>
nnoremap <Leader>d :BD <CR>

"remap leader key
"let mapleader="'"


" augroup my-glyph-palette
"     autocmd! *
"       autocmd FileType fern call glyph_palette#apply()
"         autocmd FileType nerdtree,startify call glyph_palette#apply()
"       augroup END

"let g:fern_git_status#disable_submodules = 1
"let g:fern_git_status#disable_directories = 1
"let g:fern_git_status#disable_ignored = 1
"let g:fern_git_status#disable_untracked = 1

"для Prettier
nnoremap <Leader>p :Prettier<CR>
"js
hi def link jsObjectKey Type

"vue
let g:vim_vue_plugin_use_scss = 1
let g:vim_vue_plugin_load_full_syntax = 1
let g:vim_vue_plugin_highlight_vue_attr = 1
let g:vim_vue_plugin_highlight_vue_keyword = 1

"css colors
let g:Hexokinase_highlighters = [ 'sign_column' ]

syntax enable
syntax sync fromstart

**Comment by voldikss** [comment] 2020-09-05 12:33
> source $HOME/.vim/plug-config/floaterm.vim

What's the content of `plug-config/floaterm.vim`?

**Comment by timsofteng** [comment] 2020-09-05 13:12
> > source $HOME/.vim/plug-config/floaterm.vim
> 
> What's the content of `plug-config/floaterm.vim`?

let g:floaterm_width=0.85
let g:floaterm_height=0.85

let g:floaterm_keymap_toggle = '<C-t>t'
let g:floaterm_keymap_next   = '<C-t>n'
let g:floaterm_keymap_prev   = '<C-t>p'
let g:floaterm_keymap_new    = '<C-t>o'
let g:floaterm_keymap_kill   = '<C-t>q'


"invoked programs
nnoremap <Leader>nnn :FloatermNew nnn <CR>
nnoremap <Leader>lg :FloatermNew lazygit <CR>

**Comment by timsofteng** [comment] 2020-09-05 13:48
So have you reproduce it?
Can it be fixed?

Thanks

**Comment by timsofteng** [comment] 2020-09-05 13:49
By the way `:FloatermNew nnn` works ok in this way. It can be closed without any issues.

**Comment by voldikss** [comment] 2020-09-05 13:49
> So have you reproduce it?
> Can it be fixed?
> 
> Thanks

Yes, it has existed for a long time(only in Vim).

**Comment by timsofteng** [comment] 2020-09-05 13:54
> Yes, it has existed for a long time(only in Vim).

Sorry, I'm not sure I correctly understand You.
Is it mean you cannot fixed it?

**Comment by voldikss** [comment] 2020-09-05 14:01
> Is it mean you cannot fix it?

I think I can fix it.

> Sorry, I'm not sure I correctly understand You.

I reproduced it just now, and then I tried `git checkout ...` and found that this bug has existed for a long time but I even wasn't aware of it until just now.

**Comment by timsofteng** [comment] 2020-09-05 14:06
> I reproduced it just now, and then I tried `git checkout ...` and found that this bug has existed for a long time but I even wasn't aware of it until just now.

Got it. Thanks for fast support.
I will waiting for fix.

p.s Do you remember my another issue about nnn bug? When you try open something in nnn with "o" button. This bug is still exist.

**Comment by voldikss** [comment] 2020-09-05 14:15
Oh, this is not a bug, it's a feature! :joy:

Put this line to your vimrc and it should be work!

```vim
let g:floaterm_autoclose = 1
```

If I set `g:floaterm_autoclose` to 0 in neovim, pressing `q` will quit lazygit and leaves an empty window like this.

![image](https://user-images.githubusercontent.com/20282795/92306906-3da46080-efc5-11ea-8169-b32764158804.png)

But in vim, whose terminal implemention is not the same as neovim's. Even it also leaves an empty window however we can not see the messages like `[Process exited 0]`(Don't know why)...

**Comment by voldikss** [comment] 2020-09-05 14:18
> p.s Do you remember my another issue about nnn bug? When you try open something in nnn with "o" button. This bug is still exist.

Yes, I have no solutions yet.

**Comment by voldikss** [comment] 2020-09-05 14:18
Let me close this issue as it must be solved.

**Closed by voldikss** 2020-09-05 14:18 UTC
Labels: lazygit

**Comment by timsofteng** [comment] 2020-09-05 14:34
`let g:floaterm_autoclose = 1`

Great!
Thanks a lot!:)
It works now.

P.s I found one more little but in NNN. I'll open new issue for it soon.
