### ISSUE TITLE
fzf wrapper doesn't work if autochdir is set

### ISSUE THREAD

**Issue by noib3** [voldikss/vim-floaterm#154] opened 2020-08-24 16:16 UTC
### To Reproduce

- Use the minimal vimrc

  ```vim
  set autochdir
  ```

- set `FZF_DEFAULT_COMMAND='fd . --base-directory ~ --type f --hidden'`

- Steps to reproduce the behavior:
  1. `set autochdir` in your (neo)vim config
  2. open any file not in the home directory, e.g. `$ nvim ~/test/some_file.txt`
  3. call `:FloatermNew fzf`
  4. choose any other file

a new buffer will be open but it'll be empty, and `:!pwd` prints the old directory instead of the new one. 

### Enviroment
 - OS [e.g. Arch Linux]: macOS
 - Version [e.g. NVIM v0.5.0-fa9b057]: `NVIM v0.4.4`
 - Checkhealth info [run `:checkhealth` and post the messages]: `checkhealth` is fine

**Comment by voldikss** [comment] 2020-08-25 00:47
Hi @n0ibe 

This issue was caused by `export FZF_DEFAULT_COMMAND='fd . --base-directory ~ --type f --hidden'`. The fzf gets the filepath and treat it as relative to the current directory. However, the argument `--base-directory` imply that the filepath was relative to the `$home` instead. As the result, it made the plugin open a file which has the wrong path.

Unfortunely there is no solutions at this moment and I've confirmed this issue also could be reproduced when using https://github.com/junegunn/fzf.vim. 

So either `set noautochdir` or stopping pass  `--base-directory` argument to the executable could be the compromising solution.

**Comment by n0ibe** [comment] 2020-08-25 08:29
I used to use junegunn's [vim plugin](https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim) before switching to Floaterm, and it worked correctly with both `set autochdir` and `--base-directory` (unfortunately I have to use both of them), so a solution is definitely possible.

Use `Plug 'junegunn/fzf'` to install it, assuming you're using vim-plug. Then simply `:FZF` to call the command.

**Comment by voldikss** [comment] 2020-08-25 08:48
I’ve reproduced the issue in fed.vim when using ‘Files’ instead of ‘FZF’. 
So it seems works fine for FZF. I’ll check the solution, thanks.

**Comment by voldikss** [comment] 2020-08-25 09:11
Hi @n0ibe 

I've tried `:FZF` and unfortunely the issue got reproduced, too(I've made a gif, see below). I have no idea why it behaviors differently for you and me. But let me mark this issue as `bug` and I'll try to solve it by checking the solution you mentioned above.

![Peek 2020-08-25 17-05](https://user-images.githubusercontent.com/20282795/91155734-d26dab00-e6f5-11ea-98fb-502484d4fff8.gif)

**Comment by n0ibe** [comment] 2020-08-25 09:35
@voldikss You're right, simply `:FZF` still reproduces the issue. Try `:FZF ~`, that should work.

**Comment by voldikss** [comment] 2020-08-25 09:38
got it

**Comment by adigitoleo** [comment] 2020-09-30 01:45
@n0ibe 
You might not need `:Floaterm fzf` anymore, since fzf uses a floating window by default now (https://github.com/junegunn/fzf/commit/c60ed1758315f0d993fbcbf04459944c87e19a48), however if you do, I think the problem is with your fzf command. I use ripgrep like this:

```
        export FZF_DEFAULT_COMMAND='rg --files --hidden $(pwd)'
```
and for me `:FZF` works as expected, even with `autochdir` (and `:FloatermNew fzf` also works). I haven't used `fd`, but  I think you need `$(pwd)` instead of `.` somewhere.

**Comment by voldikss** [comment] 2021-01-08 11:45
Closed by https://github.com/voldikss/vim-floaterm/issues/154#issuecomment-701109739

**Closed by voldikss** 2021-01-08 11:45 UTC
Labels: FAQ, fzf
