### ISSUE TITLE
autoclose=1 option is broken

### ISSUE THREAD

**Issue by wookayin** [voldikss/vim-floaterm#232] opened 2021-01-14 04:30 UTC
### Describe the bug

--autoclose=1 does not work

### To Reproduce

```
:FloatermNew --autoclose=1 /bin/false
```

It should not close the window and show some messages, as documented:

> 1: Close window if the job exits normally, otherwise stay it with messages like [Process exited 101]

### Enviroment
 - OS [e.g. Arch Linux]: Linux
 - Version [e.g. NVIM v0.5.0-fa9b057]: 0.4.2 & 0.5.0 nightly
 - Checkhealth info [run `:checkhealth` and post the messages]:

### Screenshots(Optional, GIF is better)

N/A

**Comment by wookayin** [comment] 2021-01-14 04:32
It ignores `--autoclose 0` as well.

**Comment by voldikss** [comment] 2021-01-14 05:09
Strange... I can not observe it on my machine
![Peek 2021-01-14 13-08](https://user-images.githubusercontent.com/20282795/104547502-ada8ae80-5669-11eb-8d26-1a1c24046b4e.gif)

**Comment by voldikss** [comment] 2021-01-14 14:15
It seems caused by others. You may try using a minimal vimrc as shown in the gif. 

Closing this issue, reopen/reply it if necessary.

**Closed by voldikss** 2021-01-14 14:15 UTC

**Comment by wookayin** [comment] 2021-01-14 20:17
Sorry, `--autoclose` works well. The reason I was experiencing this is due to another bug.
