### ISSUE TITLE
floaterm command not found since the rework of edita

### ISSUE THREAD

**Issue by Matts966** [voldikss/vim-floaterm#268] opened 2021-02-28 09:53 UTC
### Before reporting

- Please make sure you have searched through the [F.A.Q.](https://github.com/voldikss/vim-floaterm/issues?q=label%3AFAQ) first.

- Please make sure you are using the latest version of this plugin.

- It's better to use English as it's more friendly to other non-Chinese native users.

#### If you are using vim(not neovim), fill in the following blanks

- Output of `vim --version`:

```
NVIM v0.5.0-dev+nightly-2-g78f0f00
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto
-DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210127-11270-11bser6/build/config -I/tmp/neovim-20210127-11270-11bser6/src -I/usr/local/include -I/tmp/neovim-20210127-11270-11bser6/deps-build/include
-I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210127-11270-11bser6/build/src/nvim/auto -I/tmp/neovim-20210127-11270-11bser6/build/include
Compiled by matts966@matts966-lab.local

Features: +acl +iconv +tui
See ":help feature-compile"

      system vimrc: "$VIM/sysinit.vim"
      $VIM: "/usr/local/Cellar/neovim/HEAD-78f0f00/share/nvim"

Run :checkhealth for more info
```

- Platform: 

  - [ ] Linux
  - [x] Mac OS X
  - [ ] Windows

#### If you are using neovim, just run `:checkhealth floaterm` and post the content
below.

```markdown
health#floaterm#check
========================================================================
  - OK: Terminal feature is OK
  - OK: Floating window feature is OK
  - OK: nvr is OK


```

#### Configurations related to vim-floaterm in vimrc(i.e. `g:floaterm_xxx`):

```vim
Plug 'voldikss/vim-floaterm', { 'commit': 'c2c8c5a' } # This commit spec prevents error.
Plug 'voldikss/fzf-floaterm', { 'on': 'Floaterms' }
let g:floaterm_autoclose = 1
let g:floaterm_keymap_toggle = '``'
let g:floaterm_gitcommit = 'split'
let g:floaterm_width = 0.9
let g:floaterm_height = 0.9
nnoremap <leader>gg <CMD>silent! wa!<CR><CMD>FloatermNew lazygit<CR>
nnoremap <leader>` <CMD>Floaterms<CR>
nnoremap <leader>d <CMD>FloatermNew<CR>
```

### Describe your question, feature request, or bug.

Since [this commit](https://github.com/voldikss/vim-floaterm/commit/2984c84a7859387abbc4dd57eff22c2d264a9895), `floaterm` command fails with `floaterm command not found` error.

### Steps to reproduce

Using the minimal vimrc

```vim
set nocompatible
set hidden
set termguicolors
set runtimepath^=/path/to/vim-floaterm
filetype plugin indent on
syntax on
```

1. `:FloatermNew`
2. `floaterm`

### Actual behaviour

`zsh: command not found: floaterm`

### Expected behaviour

New buffer is opened.

### Screenshots(Optional, GIF is better)

https://user-images.githubusercontent.com/28551465/109414406-18cdfa80-79f6-11eb-9f39-63e8870c225c.mov

**Comment by voldikss** [comment] 2021-02-28 10:12
Seems that you are not using the latest version of the plugin. Could you upgrade and try again?

**Comment by Matts966** [comment] 2021-02-28 21:10
Thank you for quick response!

I used the latest repo cloned from github for the demo video. The setting is for my current use to avoid this error.

**Comment by voldikss** [comment] 2021-02-28 23:38
Run `echo $PATH` inside the floaterm and give me the output.

**Comment by voldikss** [comment] 2021-03-01 11:10
I personally dislike leaving over too much suspended issue on the GitHub Dashboard. So I will close the issue due to no reply for a long time. But you can still reply when at your leisure.

**Closed** 2021-03-01 11:12 UTC
Labels: wait for reply

**Comment by Matts966** [comment] 2021-03-01 16:43
@voldikss 

Sorry for my late reply... I could not use my PC.

Tha latest repo returns

```bash
/Users/matts966/.pyenv/shims:/Users/matts966/.pyenv/bin:/usr/local/opt/llvm/bin:/Users/matts966/google-cloud-sdk/bin:/usr
/local/opt/llvm/bin:/Users/matts966/google-cloud-sdk/bin:/Users/matts966/.pyenv/shims:/Users/matts966/.pyenv/bin:/Users/m
atts966/.zinit/polaris/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Apple/usr/bin:/usr/l
ocal/opt/llvm/bin:/Users/matts966/google-cloud-sdk/bin:/Applications/kitty.app/Contents/MacOS:/Users/matts966/go/bin:/usr
/local/opt/go/libexec/bin:/Users/matts966/.cargo/bin:/Users/matts966/esp/xtensa-esp32-elf/bin:/Users/matts966/go/bin:/usr
/local/opt/go/libexec/bin:/Users/matts966/.cargo/bin:/Users/matts966/esp/xtensa-esp32-elf/bin:/Users/matts966/go/bin:/usr
/local/opt/go/libexec/bin:/Users/matts966/.cargo/bin:/Users/matts966/esp/xtensa-esp32-elf/bin
```

and the `c2c8c5a` returns

```bash
/Users/matts966/.pyenv/shims:/Users/matts966/.pyenv/bin:/usr/local/opt/llvm/bin:/Users/matts966/google-cloud-sdk/bin:/usr
/local/opt/llvm/bin:/Users/matts966/google-cloud-sdk/bin:/Users/matts966/.pyenv/shims:/Users/matts966/.pyenv/bin:/Users/m
atts966/.zinit/polaris/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Apple/usr/bin:/usr/l
ocal/opt/llvm/bin:/Users/matts966/google-cloud-sdk/bin:/Applications/kitty.app/Contents/MacOS:/Users/matts966/go/bin:/usr
/local/opt/go/libexec/bin:/Users/matts966/.cargo/bin:/Users/matts966/esp/xtensa-esp32-elf/bin:/Users/matts966/vim-floater
m/bin/:/Users/matts966/go/bin:/usr/local/opt/go/libexec/bin:/Users/matts966/.cargo/bin:/Users/matts966/esp/xtensa-esp32-e
lf/bin:/Users/matts966/go/bin:/usr/local/opt/go/libexec/bin:/Users/matts966/.cargo/bin:/Users/matts966/esp/xtensa-esp32-e
lf/bin
```

It seems that the only difference is the `:/Users/matts966/vim-floaterm/bin/` is loaded or not.

Also, my `.zshrc` contains

```zsh
if [[ $VIM ]]; then
    alias vim=floaterm
    export EDITOR=floaterm
else
    alias vim=nvim
    export EDITOR=nvim
fi
```

**Comment by voldikss** [comment] 2021-03-02 01:33
Strange but I can not reproduce the issue...

This might be a potential bug. But I do not use Mac, I would like to look deep into it.

**Comment by Matts966** [comment] 2021-03-02 14:37
@voldikss 
Sorry, I am busy this week so maybe we can have debug session next weekend.

Also, I would like to apologize my mistake to say the cause of this is [this commit](https://github.com/voldikss/vim-floaterm/commit/2984c84a7859387abbc4dd57eff22c2d264a9895).

I re-bisected the history and found that real cause is [this commit](https://github.com/voldikss/vim-floaterm/commit/84298d064550ad9f0811a437e25d7f1792741174#diff-159da322a2695b5b10ac64f3b53a67cb48ad1f17735d5abfdd17a39aadc79c4d). Is this reasonable?

**Comment by voldikss** [comment] 2021-03-02 14:46
> Sorry, I am busy this week so maybe we can have debug session next weekend.

Ok, that's fine.

> I re-bisected the history and found that real cause is this commit. Is this reasonable?

Could you add `echom env` before line 158 of the file [util.vim](https://github.com/voldikss/vim-floaterm/blob/master/autoload/floaterm/util.vim) and give me the output when starting floaterm?
https://github.com/voldikss/vim-floaterm/blob/84298d064550ad9f0811a437e25d7f1792741174/autoload/floaterm/util.vim#L158

**Comment by Matts966** [comment] 2021-03-02 15:03
```viml
{'EDITOR': '''/usr/local/Cellar/neovim/HEAD-24b6032/bin/nvim'' --headless --clean --noplugin -n -R -c ''set runtimepath^=/Users/matts966/vim-floaterm'' -c ''call floaterm#edita#neovim#client#open()''', 'PA
TH': '/Users/matts966/.pyenv/shims:/Users/matts966/.pyenv/bin:/Users/matts966/.zinit/polaris/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Apple/usr/bin:/usr/local/opt/llvm/
bin:/Users/matts966/google-cloud-sdk/bin:/Applications/kitty.app/Contents/MacOS:/Users/matts966/go/bin:/usr/local/opt/go/libexec/bin:/Users/matts966/.cargo/bin:/Users/matts966/esp/xtensa-esp32-elf/bin:/Use
rs/matts966/vim-floaterm/bin/', 'GIT_EDITOR': '''/usr/local/Cellar/neovim/HEAD-24b6032/bin/nvim'' --headless --clean --noplugin -n -R -c ''set runtimepath^=/Users/matts966/vim-floaterm'' -c ''call floaterm
#edita#neovim#client#open()'''}
```

**Comment by Matts966** [comment] 2021-03-02 15:23
Seems the neovim issue? I am pulling neovim HEAD.

**Comment by Matts966** [comment] 2021-03-02 15:25
But this was too old.
https://github.com/neovim/neovim/issues/11751

**Comment by Matts966** [comment] 2021-03-02 15:34
I found that modifying the block below can fix this issue (use the former `setenv` part for all nvim), and the `jobopts` is correctly passed. Maybe `nvim` `termopen`'s issue.

https://github.com/voldikss/vim-floaterm/blob/d65d2aa51914197ae6cdd17c8873fe8abdff7314/autoload/floaterm.vim#L33-L39

**Comment by voldikss** [comment] 2021-03-02 20:12
Seems this version of nvim doesn't allow an `env` parameter for `jobstart` and `termopen` (`:help jobstart-options` to check)

**Comment by Matts966** [comment] 2021-03-03 15:21
Using latest neovim fix this issue. Thank you 🙇‍♂️

Maybe, the related PR is https://github.com/neovim/neovim/pull/12937 .

**Comment by voldikss** [comment] 2021-03-03 15:33
> Maybe, the related PR is neovim/neovim#12937 .

Yes, I also think so.
