### ISSUE TITLE
FloatermToggle always creates a new terminal instance?

### ISSUE THREAD

**Issue by vinchi777** [voldikss/vim-floaterm#17] opened 2019-10-29 07:48 UTC
After upgrading the plugin, toggling will now always load a new terminal. Previously it would keep the previous terminal state.

This makes opening the terminal window slow as It has to load the zsh everytime. Also would clear out the terminal prints from the previous commands.

**Comment by voldikss** [comment] 2019-10-29 08:13
There might be some problem with this line, however I cannot reproduce it currently.
https://github.com/voldikss/vim-floaterm/blob/45f2f6010a41311eb2db4b627a6cd7e4b618f18d/autoload/floaterm.vim#L37

Or you can try `:echo g:floaterm_buflist` to see what the output is.

**Comment by giorgioprevitera** [comment] 2019-11-01 12:24
Same for me, these are the steps to reproduce (currently on `09cf3e2`):
- use the `:FloatermToggle` command to open a new terminal buffer
- run any command, e.g. `date`
- use the `<C-\><C-n>:FloatermToggle<CR>` to toggle the current buffer
- toggle the terminal back on with `:FloatermToggle` - This will create a new terminal buffer with a new shell session in it, losing the output of the `date` command

**Comment by voldikss** [comment] 2019-11-01 14:52
> * toggle the terminal back on with `:FloatermToggle` - This will create a new terminal buffer with a new shell session in it, losing the output of the `date` command.
> 
> The expected behaviour is to toggle the previous terminal buffer back on.

Hi @giorgioprevitera I just executed those steps and it works normally for me.

Also I have tried your dotfiles and sadly I still cannot reproduce this issue...

**Comment by giorgioprevitera** [comment] 2019-11-01 14:55
My neovim version:
```

**Comment by voldikss** [comment] 2019-11-01 15:00
Would you give your nvim version detail?

In addition, would you mind debugging it?

- Add `echomsg string(g:floaterm_buflist)` after line36 in `autoload/floaterm.vim` file
- Use the :FloatermToggle command to open a new terminal buffer
- Run any command, e.g. date
- Use the <C-\><C-n>:FloatermToggle<CR> command to toggle the current buffer off
- Toggle the terminal back on with :FloatermToggle - This will create a new terminal buffer with a new shell session in it, losing the output of the date command.
- Type `:message` and show the message

**Comment by mrprofessor** [comment] 2019-11-02 16:45
I just checked out to this commit.
https://github.com/voldikss/vim-floaterm/commit/6ffb68a79031a1a797f63e403b8deb36c597b17c
 
It fixes both #17 and #16 . Will definitely help debug when I get any breathing space from my work. Thanks for creating the plugin though. @voldikss

**Comment by moevis** [comment] 2019-11-24 12:59
I'm still got the same problem. It was always creating a new terminal.
After inserting a debug code `echomsg string(g:floaterm_buflist)` and `echomsg string(s:sum(g:floaterm_buflist))` at line36 in autoload/floaterm.vim.

The first message outputed was `[]`.
And then I toggle the terminal and toggle again, the second message I got was:
```
[2]
2
[0]
0
```

The next message was:
```
[0, 3]
3
[0, 0]
0
```

the 4th was
```
[0, 0, 4]
4
[0, 0, 0]
0
```

I got a new terminal everytime. My machine is macOS 10.14, and my neovim version is :
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
```

**Comment by voldikss** [comment] 2019-11-24 15:42
Thank @moevis for helping with debugging. It seems this issue occurs only on Mac OS. 

The problem is the first branch in the `if-else` statement here was judged to be `v:false(0)`,which should be `v:true(1)`.

https://github.com/voldikss/vim-floaterm/blob/5150c93501ce4d9ab7ee978a1dc161de2570ca40/autoload/floaterm.vim#L42-L49

Could someone help debug again?

- Add `echomsg found_bufnr . '    ' . bufexists(found_bufnr)` before line 42 in `autoload/floaterm.vim`
- Type `:FloatermToggle` to open a new terminal buffer
- Type `<C-\><C-n>:FloatermToggle<CR>` to toggle the current floating buffer off
- Type `:FloatermToggle` again
- Type `:message` and give me the message

**Comment by moevis** [comment] 2019-11-25 01:44
@voldikss I opened terminal 4 times and got following output:
```
2 0
3 0
4 0
```

**Comment by voldikss** [comment] 2019-11-25 02:27
Thanks for debugging.

Hummm cannot figure it out yet.😔

Leave it aside. I will try to fix it one month later.

**Comment by voldikss** [comment] 2019-12-23 07:16
Hi all. I think I just found that ringleader!

The `hidden` option, which is closed (`:help hidden`) by default, will unload the floating terminal buffer when you use `:FloatermToggle` to hide that window. Therefore, when you toggle it again, the plugin has to create a new one.

So the solution is putting `set hidden` in your `vimrc` to prevent from unloading the buffer. Could you test it and give me some feedbacks?

In addition, I am considering whether it is a well-designed behaviour to `set hidden` in the `plugin/floaterm.vim` file...

**Comment by vinchi777** [comment] 2019-12-23 07:22
Just tested, It works!

**Comment by voldikss** [comment] 2019-12-24 02:37
I think this issue should get fixed, so I will close it. If it still exist, feel free to reopen it.

**Closed by voldikss** 2019-12-24 02:37 UTC
Labels: bug
