### ISSUE TITLE
lightline (active) lost when closing floating terminal

### ISSUE THREAD

**Issue by oblitum** [voldikss/vim-floaterm#19] opened 2019-11-06 18:15 UTC
I use lightline and it has an appearance for focused window that is different than unfocused ones. When opening the floaterm the background window becomes unfocused and lightline changes accordingly, but when closing floaterm lightline doesn't update. `:call lightline#update()` forces the refresh.

**Comment by voldikss** [comment] 2019-11-06 23:54
That's strange, since normally lightline will update automatically when your switched back from floaterm according to [this line in lightline.vim](https://github.com/itchyny/lightline.vim/blob/1afe1e9bd5726550014d78ee244499d65beeb686/plugin/lightline.vim#L18)

Or you can check it, type `:autocmd BufEnter` and see whether it contains `lightline#update()`

Can not reproduce now.

**Comment by oblitum** [comment] 2019-11-07 01:00
Yes, `lightline#update()` there.

**Comment by oblitum** [comment] 2019-11-07 01:03
It only happens when I `exit` from terminal. If I switch out of the terminal, or toggle it, there's no issue.

**Comment by voldikss** [comment] 2019-11-07 05:46
Can reproduce this issue. It seems that lightline will be disable in the terminal buffer.
So currently I have no ways to fix this. However, since lightline has registered an `autocmd CursorMove` event [here](https://github.com/itchyny/lightline.vim/blob/53bd3279da783cd5c1b1fafb4ff31077e81b6333/plugin/lightline.vim#L25) to update the statusline, moving the cursor will activate your statusline.

**Comment by voldikss** [comment] 2019-11-07 05:47
What do you think about this @oblitum

**Comment by oblitum** [comment] 2019-11-07 05:55
Indeed, it's refreshed when cursor moves. So, it's not that problematic. It's an annoying detail. I'm not sure whether you should leave it as wontfix or not.

**Comment by voldikss** [comment] 2019-11-07 06:16
OK, since it's not that problematic , so I just mark it wontfix.

**Comment by oblitum** [comment] 2020-02-20 06:40
This has become more problematic. Now when moving the cursor, lightline doesn't come back.

When the term is toggled off, this doesn't happen. Only when I `exit` from float term it happens (which effectively destroys it, contrary to toggling).

**Comment by oblitum** [comment] 2020-02-20 06:44
lightline has removed the `CursorMoved` event in master.

**Comment by kazhala** [comment] 2020-02-20 12:01
@voldikss I'm still getting the issue where the lightline is not properly being updated after exiting a floaterm, toggle works fine. Unfortunately [fdac46a](https://github.com/voldikss/vim-floaterm/commit/fdac46a467365701fb8aef8a0fd1c09111cb1484) did not fix it for me. I'm on macOS with neovim
![floaterm-bug-demo](https://user-images.githubusercontent.com/43941510/74931933-ca763b00-5434-11ea-8e97-cc819d838c30.gif)

**Comment by kazhala** [comment] 2020-02-20 12:05
Or maybe is lightline users who should implement this fix, it seems only related to lightline. Not sure if it's possible, maybe registering a lightline update event by lightline user is possible. I'll have a look on lightline api and see

**Comment by voldikss** [comment] 2020-02-20 12:29
Hi @oblitum , did fdac46a fix this issue on your machine?

**Closed** 2020-02-20 12:33 UTC
Labels: bug

**Comment by voldikss** [comment] 2020-02-20 12:35
Hi @kazhala , e8c7d1b should fix this issue.

**Comment by oblitum** [comment] 2020-02-20 15:53
Thx, it's fixed now.
